const teamsToId = {
    Hawks: 1,
    Celtics: 2,
    Nets: 3,
    Hornets: 4,
    Bulls: 5,
    Cavaliers: 6,
    Mavericks: 7,
    Nuggets: 8,
    Pistons: 9,
    Warriors: 10,
    Rockets: 11,
    Pacers: 12,
    Clippers: 13,
    Lakers: 14,
    Grizzlies: 15,
    Heat: 16,
    Bucks: 17,
    Timberwolves: 18,
    Pelicans: 19,
    Knicks: 20,
    Thunder: 21,
    Magic: 22,
    "76ers": 23,
    Suns: 24,
    "Trail Blazers": 25,
    Kings: 26,
    Spurs: 27,
    Raptors: 28,
    Jazz: 29,
    Wizards: 30
}

const idToTeam = [
    "Placeholder",
    "Hawks",
    "Celtics",
    "Nets",
    "Hornets",
    "Bulls",
    "Cavaliers",
    "Mavericks",
    "Nuggets",
    "Pistons",
    "Warriors",
    "Rockets",
    "Pacers",
    "Clippers",
    "Lakers",
    "Grizzlies",
    "Heat",
    "Bucks",
    "Timberwolves",
    "Pelicans",
    "Knicks",
    "Thunder",
    "Magic",
    "76ers",
    "Suns",
    "Trail Blazers",
    "Kings",
    "Spurs",
    "Raptors",
    "Jazz",
    "Wizards"
]

exports.teamsToId = teamsToId;
exports.idToTeam = idToTeam;